services:
    omouren_external_var_dumper.var_dumper.server_connection:
        class: Omouren\ExternalVarDumperBundle\Services\Connection
        parent: var_dumper.server_connection
        calls:
            - setHttpClient: ['@http_client']
